### ISSUE TITLE
Generator resume arguments?

### ISSUE THREAD

**Issue by cameronelliott** [withoutboats/propane#10]
This project is fantastic! You made my night, seriously.

But, I have one question. 

Does this package support resume arguments?
like `let x = yield String::from("fizz");`

If not, can you suggest or explain how I might explore adding that?

Thanks,
Cameron

**Comment by cameronelliott** [comment]
When I wrote this, I wasn't even sure how to supply types to the build-in generators, but I figured it out:

```
   let mut mysink = move |_: i32| loop {
        let a = yield;
        if a % 100000 == 0 {
            println!("got a {}", a);
        }
    };
```
`a` will be an i32 because of the argument to the generator.

**Comment by withoutboats** [comment]
This library is specifically for a kind of generator that makes an Iterator from a function. It's intentional that it doesn't expose the ability to take arguments.
